services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3060:3060
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
