version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - 3060:3060
    develop:
      watch:
        - action: rebuild
          path: .
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
